[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[project]
name = "smytm"
version = "1.1"
description = "CLI utility for searching and downloading musics / audios from YouTube (Music)."
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "SmileLulz" }]
license = "GPL-3.0-only"
license-files = ["LICENSE"]
dependencies = [
    # Intentionally empty, all dependencies are checked during runtime
]

[project.urls]
Repository = "https://github.com/SmileLulz/smytm"

[project.scripts]
smytm = "smytm.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["smytm"]

[tool.hatch.build.targets.sdist]
include = [
    "/smytm",
    "/README.md",
    "/LICENSE",
]

[tool.ruff]
line-length = 100

[tool.pytest.ini_options]
pythonpath = ["."]
